kotlin.code.style=official
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mc_version=1.20.1
fabric_api_version=0.92.6+1.20.1
fabric_loader_version=0.17.2

mod_id=create_jetpack
mod_version=0.0.0-dev
release_type=beta
mod_name=Create Jetpack
mod_author=possible_triangle
maven_group=com.possible-triangle

kotlin_fabric_version=1.13.3+kotlin.2.1.21

repository=pssbletrngle/createjetpack
modrinth_project_id=UbFnAd4l
curseforge_project_id=655608
