org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
kotlin.code.style=official

mc_version=1.21.1
neoforge_version=21.1.219

mod_id=create_jetpack
mod_version=0.0.0-dev
release_type=release
mod_name=Create Jetpack
mod_author=possible_triangle
maven_group=com.possible-triangle

kotlin_forge_version=5.8.0

repository=pssbletrngle/createjetpack
modrinth_project_id=UbFnAd4l
curseforge_project_id=655608
