name = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d62772562dc566bac0da4b42acc13150fd1e0efffa43e7fe6eff2760bea78b2f"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
